### ISSUE TITLE
How to do Unit Testing of CRUD operations perform with EF

### ISSUE THREAD

**Issue by nexawo** [thomasgalliker/EntityFramework.Toolkit#11]
Hello, I am a newbie and I have created a CRUD operation using Entity FrameWork. Now I want to do Unit Testing of this project but I can't find relevant help. So, if someone can perform a unit testing of my project this will be a great help for me.

Here is the link of my project: https://github.com/nexawo/EntityFrameWork

**Comment by thomasgalliker** [comment]
I see that you're injecting the DbContext (EmployeeContext) directly into the API controllers. I usually don't do this for two reasons: First, you have limited testing possibilities when you inject the DbContext directly. You can (afaik) only use the InMemory database context in this case which I would not recommend. The second reason is that I often have logic between the controllers and the data access layer. I dont want to bloat my controllers with business logic.

Now, how can you test the backend logic? I would recommend you to use the provided interfaces in EntityFramework.Toolkit. Instead of injecting EmployeeContext I would (I actually do so) inject IEmployeeRepository (which abstracts the implementation GenericRepository<Employee>). Now, I you want to write a unit test for EmployeeController, just mock the IEmployeeRepository away... I'm using Moq library for this purpose but there are several others on the market.

Do you think this works in your case?
